# permissions for end users to edit inputclasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inputclass-editor-role
rules:
- apiGroups:
  - core.deppy.io
  resources:
  - inputclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.deppy.io
  resources:
  - inputclasses/status
  verbs:
  - get
