# permissions for end users to view platformoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platformoperator-viewer-role
rules:
- apiGroups:
  - core.deppy.io
  resources:
  - platformoperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.deppy.io
  resources:
  - platformoperators/status
  verbs:
  - get
