---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - core.deppy.io
  resources:
  - inputs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.deppy.io
  resources:
  - platformoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.deppy.io
  resources:
  - platformoperators/finalizers
  verbs:
  - update
- apiGroups:
  - core.deppy.io
  resources:
  - platformoperators/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.deppy.io
  resources:
  - resolutions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.deppy.io
  resources:
  - resolutions/finalizers
  verbs:
  - update
- apiGroups:
  - core.deppy.io
  resources:
  - resolutions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operators.coreos.com
  resources:
  - catalogsources
  verbs:
  - get
  - list
  - watch
